### PR TITLE
Fix exception handling for JPype 0.7

### PR DESCRIPTION
**Pull request by baztian**
thanks @Thrameos  for pointing out the issue (#102)

### CODE REVIEW

**Comment by baztian** [comment]
@Thrameos you mentioned some exception handling changes in #102. I don't really get how it changed. Also it's been a while back I wrote the exception handling code.
Can you please give me some advice on how to change the code accordingly?

**Comment by Thrameos** [comment]
Should be covered in jpype-project/jpype#498 and laughingman7743/PyAthenaJDBC#85

The original exception code caught a dummy class that held the real exception as the first argument but the version directly throws the exception.  There was a common pattern that both versions are supposed to be able to use using JException, but thus far I have seen a lot of code that get into the arguments.

Hopefully these two threads have enough to help.  If not just reply an I will take a deeper look at your structure.

**Comment by baztian** [comment]
Thanks @Thrameos. I tried two different approaches to deal with exceptions in this PR. Looking deeper into it it seems I'm (now) catching the exceptions correctly. But the unit test uses str/toString on the exception and is getting the wrong output. The code works with the older JPypes and with Jython.

The output of [the test](https://github.com/baztian/jaydebeapi/blob/fix-exceptions-for-new-jpype/test/test_mock.py#L86) can be found in [the travis job output](https://travis-ci.org/baztian/jaydebeapi/jobs/556477654#L386).

It seems to be a JPype 0.7 shortcomming. Can you please have another look on this?

**Comment by baztian** [comment]
One other thing in JPype 0.7 I don't really get is that string conversion seems to be changed for non Pyhton 3 versions. https://travis-ci.org/baztian/jaydebeapi/jobs/556477652#L286 works with the old JPype version: https://travis-ci.org/baztian/jaydebeapi/jobs/556477652#L498
@Thrameos any ideas?

**Comment by Thrameos** [comment]
Well ``str(exception)`` should be calling ``exception.toString()`` which should be what you expect.  It looks like there may be a bug in jpype with this regard.

Seems like the line 65 in ``jpype/_jexception.py`` 
```
     def __str__(self):
        return str(self.getMessage())
```

should read as
```
     def __str__(self):
        return str(self.toString())
```

**Comment by Thrameos** [comment]
As to the other question, are you referring to string conversions in general such as returning ``java.lang.String`` rather than Python strings or something else?

**Pull request closed without merging**
