### PR TITLE
Try to fix some travis issues

### PR DESCRIPTION
**Pull request by baztian**

### CODE REVIEW

**Comment by baztian** [comment]
Had to downgrade JPype1 to 0.7.2 because of https://github.com/jpype-project/jpype/issues/754

**Comment by Thrameos** [comment]
JPype 0.7.1 suffers from a packaging issue with numpy.   An attempt to upgrade the packaging system built numpy only binaries for that one release.   It was determined (after several months of work) that it the model that JPype with a binary file labeled as an "extra" was in fact was not possible in the packaging system.   The recommended stable version for 2.7 will remain at 0.7.0.   The recommended stable for 3.5-3.8 is 0.7.5 with is the final release prior to the 0.8.0 when the core rewrite is finally complete and the last return contract is fixed (JChar takes a number and returns a string).  JPype 0.8 will be supported with a stable public API until 0.9 is released with the Java to Python bridge.

**Comment by Thrameos** [comment]
You may want to use nox rather than tox for your CI.   In nox, you can easily add a session for each version you would like to test and have different jobs executing each session rather trying to run everything in one job.   We also transitioned from travis to azure because it gave the ability to manage multiple pile lines such as a test and release pipeline.  The patterns are shown in the ``.azure`` directory under the current JPype master.

**Comment by baztian** [comment]
Thanks @Thrameos for mentioning nox. I might get have a closer look. For most of my current projects I'm using Github Actions. Why did you choose Azure in favour of Github Actions?

**Comment by Thrameos** [comment]
I selected Azure because I need to be able to cut releases for Linux, Windows, and OSX using the same system.   We were using Travis for Linux and Appveyor for Windows but having mixed CI system meant something was always down or needing repair.  I didn't look over Github Actions so it may be similar.  (darn similar)

**Comment by Thrameos** [comment]
At least in the latest hash is working on integers.

```
import jpype
import jpype.imports
jpype.startJVM()
import java
print(hash(java.lang.Integer))
print(hash(java.lang.Integer(1)))
```

There was a bug at some point were the ``__eq__`` was set and ``__hash__`` was not resulting in triggering the Python behavior of unhashable type.  Those must be set together on all levels of the class hierarchy or bad things happen.

**Pull request merged**
