### PR TITLE
added support of Parameters passing to getConnection

### PR DESCRIPTION
**Pull request by testlnord**
I've made it for my issue https://github.com/baztian/jaydebeapi/issues/16.
Now I can connect to SQL Server with domain-based authentication. Like this:

``` python
connection = jaydebeapi.connect("net.sourceforge.jtds.jdbc.Driver",
                                  ['jdbc:jtds:sqlserver://server:1433/database', 
                                    {'user':'my.user.name',
                                     'password':'mYpa55w0RD',
                                     'domain':'DOMAINNAME'}
                                  ],
                                 '/path/to/jar/jtds-1.2.5.jar')
```

### CODE REVIEW

**Comment by baztian** [comment]
Thanks for the PR!
One thing I see in you PR is that there is no test covering the new feature. Furthermore it would be nice if you could add some documentation to the README.rst.

**Comment by testlnord** [comment]
Thanks for reply. 
I'll add some tests and docs in a couple of weeks.

**Comment by testlnord** [comment]
Can you give some hints on running your tests. I haven't managed to run them locally.

**Comment by testlnord** [comment]
Hello again, my couple of weeks finally passed. 
I've added tests and documentations. Also I've updated your developer notes a little.
I haven't figure out how to increase coverage. All my changes are in protected functions and I don't want to write tests for them. So I just copied your hsqldb tests changing only connection.

**Comment by baztian** [comment]
Hi, thanks for your change which is awesome! 
You are not executing the test in. Travis. Yml  File. That's why the coverage check won't honour your new test. 
The documentation is too muvh copy and paste for me. Can you please avoid the duplication of the unnecessary query samples? 

Thanks for your great work!

**Comment by testlnord** [comment]
Done. Still getting -0.5% though. ((

**Comment by testlnord** [comment]
Sorry for all this mess. I forgot to switch to another branch.

**Comment by testlnord** [comment]
YES! :tada: 

I've managed to collect coverage for jython tests. 

I install older version of coverage, which can be ran with jython. Then I convert its output to newer format and then collect results with coveralls installed from python.

**Comment by baztian** [comment]
Can you please explain why you needed to change so much coverage and jython setup stuff?

**Comment by testlnord** [comment]
To make coveralls eat coverage results for jython tests. 

I need to install both coveralls from ordinary python and jython. Than I install older version of coverage and run it via jython to collect coverage info. Then convert it from older format to newer one. At last I send all coverage info to coveralls.

**Comment by baztian** [comment]
Thanks @testlnord. Do I understand it correctly that coverage on the master branch doesn't cover jython as well. (Sorry it's been a time ago I've set it up)

**Comment by baztian** [comment]
@testlnord what do you say to my alternative approach in `connection-properties' branch?

**Comment by testlnord** [comment]
@baztian 

Yes, coverage for jython tests were ignored so coveralls doesn't count them as covered. So coverage has decreased when I added my code.

Here's line 47 from your `.travis.yml` file:

> if [ -z "$JYTHON" ]; then PY="coverage run --source jaydebeapi"; else PY="python" ;fi

**Comment by testlnord** [comment]
@baztian as I understood you moved all properties creation to `_jdbc_connect_*` functions and removed some helpers. Seems nice. Let's be it.

**Comment by baztian** [comment]
The main change is that we now have a (new) separate url parameter and a driver_args parameter which can either be a sequence or a dict. So it's an API change. It will break compatibility to priror versions but the api design feels less tricky to me.

**Comment by baztian** [comment]
Thanks again for you efforts. I've now merged the feature from my branch. The Jython coverage is not yet included though.

**Comment by baztian** [comment]
What is `convert_coverage.py` for? Why do you need this for Jython especially?

**Comment by testlnord** [comment]
You need older version of `coverage` for jython (without multithreading). But older `coverage` produce different output. And `coverall` doesn't understand it. So I wrote a script to convert older `coverage` log to new one.

**Comment by baztian** [comment]
@testlnord I Jython coverage working with a recent coverage version. No issues with mutlithreading so far. The only thing was to use cpython to upload to coveralls as there are some ssl issues in Jython. See shazow/urllib3#1133

**Pull request closed without merging**
